### ISSUE TITLE
Night Mode Switch show hide option

### ISSUE THREAD

**Issue by bvalasek** [lukasCerv/homebridge-xiaomi-devices#1]
Great plugin, thanks. Is there a setting where I can hide Night Mode Switch. In my case for vacuum cleaner it seems to not have any effect. I can hide it manually in Homebridge Accessories but it still shows in iOS Home app in its own tile. It could be useful to hide it on plugin level in config.

**Comment by krakonos1602** [comment]
Optional config entry was added ("showNighSwitch": true/false). You might need to clear Homebridge's device cache to make iOS tile disappear after changing the config.
